version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ../shared_db:/db  # 將主機的 ./data 資料夾掛載到 container 的 /app/data
    restart: always
    
